In [4]:
import numpy as np
# Nutrition matrix. weight, calories, fat, saturated fat, carbohydrate, protein, cholesterol
nutritions = np.array([[61, 100, 7, 2.2, 1, 7, 215], #egg
                      [156, 340, 18, 7, 44, 5, 0], # 1 cup of potatoes
                      [19, 110, 9, 3.3, 0, 6, 16], # 3 slices bacon
                      [27, 60, 2, 0.5, 8, 2, 16]]) # 1 pancake
nutritions

array([[ 61. , 100. ,   7. ,   2.2,   1. ,   7. , 215. ],
       [156. , 340. ,  18. ,   7. ,  44. ,   5. ,   0. ],
       [ 19. , 110. ,   9. ,   3.3,   0. ,   6. ,  16. ],
       [ 27. ,  60. ,   2. ,   0.5,   8. ,   2. ,  16. ]])

In [6]:
meals = np.array([[2,1,0,0], [0,1,1,1]])   # Breakfast, lunch
# Multiply the matricres together
np.dot(meals, nutritions)   # The first line is for breakfast, the second is for lunch

array([[278. , 540. ,  32. ,  11.4,  46. ,  19. , 430. ],
       [202. , 510. ,  29. ,  10.8,  52. ,  13. ,  32. ]])

In [9]:
A = np.array([[1,2,4,7],
              [13,9,13,3],
              [17,8,12,20],
              [17,20,2,5],
              [5,5,17,17]])
B = np.dot([0,0,1,0,0],A)
C = np.dot(B,[[1],[1],[1],[1]])
C

array([57])

In [10]:
np.dot([0,1,1,1,1],A)

array([52, 42, 44, 45])

A = np.array(np.zeros(4,2))

In [12]:
A

array([[ 1,  2,  4,  7],
       [13,  9, 13,  3],
       [17,  8, 12, 20],
       [17, 20,  2,  5],
       [ 5,  5, 17, 17]])

In [19]:
import numpy as np
A = np.zeros((4,2))
B = np.zeros((3,3))
C = np.zeros((2,3))

In [25]:
B*B

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [29]:
A

array([[0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.]])

In [30]:
C

array([[0., 0., 0.],
       [0., 0., 0.]])

In [33]:
np.dot(np.dot(A,C),B)

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [36]:
np.dot(B, B)

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [38]:
A = np.array([[6,1,10], [55,31,1], [11,1,7]])
B = np.array([48, 121, 41])
X = np.linalg.inv(A).dot(B)
X

array([1., 2., 4.])

In [48]:
A = np.array([[1,10,5],[5,0,0],[1,7,6]])
b = np.array([46, 30, 39])
np.linalg.inv(A).dot(b)

array([6., 3., 2.])

In [50]:
A = np.array([[0,1,8],[31,30,0],[1,4,7]])
b = np.array([29,181,42])
np.linalg.inv(A).dot(b)

array([1., 5., 3.])

In [52]:
np.linalg.solve(A, b)

array([1., 5., 3.])